from __future__ import annotations

from dataclasses import dataclass
from random import Random
from statistics import mean
from typing import Iterable, Mapping

from devices import Device
from slicing import SLICES


@dataclass(frozen=True)
class DeviceMetrics:
    """Per-device performance values generated by the simulation."""

    device_id: int
    slice_name: str
    latency_ms: float
    throughput_mbps: float
    packet_loss_pct: float


@dataclass(frozen=True)
class SliceSummary:
    """Aggregated KPIs for each network slice."""

    device_count: int
    avg_latency_ms: float
    p95_latency_ms: float
    p99_latency_ms: float
    avg_throughput_mbps: float
    avg_packet_loss_pct: float
    sla_violation_count: int
    sla_violation_rate_pct: float
    load_ratio: float


@dataclass(frozen=True)
class SimulationResult:
    """Complete simulation output for one slicing strategy."""

    mode: str
    device_metrics: list[DeviceMetrics]
    slice_summary: dict[str, SliceSummary]
    overall_sla_violation_count: int
    overall_sla_violation_rate_pct: float
    fairness_index: float
    utility_score: float


@dataclass(frozen=True)
class SliceSlaThreshold:
    """SLA target thresholds used for violation accounting."""

    max_latency_ms: float | None = None
    min_throughput_mbps: float | None = None
    max_packet_loss_pct: float | None = None


DEFAULT_SLA_THRESHOLDS: dict[str, SliceSlaThreshold] = {
    "mMTC": SliceSlaThreshold(max_latency_ms=80.0, max_packet_loss_pct=3.0),
    "eMBB": SliceSlaThreshold(min_throughput_mbps=25.0, max_packet_loss_pct=2.0),
    "URLLC": SliceSlaThreshold(max_latency_ms=10.0, max_packet_loss_pct=1.0),
}


def simulate_network_performance(
    devices: Iterable[Device],
    assignments: Mapping[int, str],
    mode: str,
    seed: int = 42,
    background_load: Mapping[str, float] | None = None,
    sla_thresholds: Mapping[str, SliceSlaThreshold] | None = None,
) -> SimulationResult:
    """Simulates latency, throughput, and packet loss for assigned devices."""
    rng = Random(seed)
    network_load = rng.uniform(0, 1)
    device_list = list(devices)
    lookup = {device.id: device for device in device_list}

    load = {slice_name: 0.0 for slice_name in SLICES}
    totals = {slice_name: 0.0 for slice_name in SLICES}

    background = {slice_name: 0.0 for slice_name in SLICES}
    if background_load is not None:
        for slice_name in SLICES:
            background[slice_name] = background_load.get(slice_name, 0.0)

    for device_id, slice_name in assignments.items():
        device = lookup[device_id]
        totals[slice_name] += device.data_rate

    for slice_name, profile in SLICES.items():
        # Add global network stress factor so all slices feel system-wide load.
        load[slice_name] = background[slice_name] + (0.25 * network_load) + (
            totals[slice_name] / profile.bandwidth_capacity_mbps
        )

    metrics: list[DeviceMetrics] = []

    for device in device_list:
        slice_name = assignments[device.id]
        profile = SLICES[slice_name]
        load_ratio = load[slice_name]
        congestion = max(0.0, load_ratio - 1.0)

        priority_latency = {1: 0.80, 2: 1.00, 3: 1.15}[device.priority]
        priority_loss = {1: 0.65, 2: 1.00, 3: 1.25}[device.priority]

        latency_ms = profile.base_latency_ms * priority_latency * (
            1.0 + (0.9 * load_ratio) + (2.5 * congestion)
        )
        latency_ms += rng.uniform(-2.0, 2.0)

        if _is_dynamic_mode(mode):
            latency_ms *= 0.92 if device.priority == 1 else 0.97

        efficiency = 1.0 - (0.22 * max(0.0, load_ratio - 0.70)) - (0.35 * congestion)
        efficiency += rng.uniform(-0.04, 0.04)

        if _is_dynamic_mode(mode):
            efficiency += 0.06 * ((4 - device.priority) / 3)

        efficiency = max(0.25, min(1.00, efficiency))
        throughput_mbps = device.data_rate * efficiency

        base_loss = {"mMTC": 1.2, "eMBB": 0.8, "URLLC": 0.15}[slice_name]
        packet_loss_pct = base_loss * priority_loss * (
            1.0 + (3.5 * congestion) + max(0.0, load_ratio - 0.80)
        )

        if _is_dynamic_mode(mode):
            packet_loss_pct *= 0.82

        packet_loss_pct += rng.uniform(-0.08, 0.12)

        metrics.append(
            DeviceMetrics(
                device_id=device.id,
                slice_name=slice_name,
                latency_ms=round(max(1.0, latency_ms), 3),
                throughput_mbps=round(max(0.0, throughput_mbps), 3),
                packet_loss_pct=round(max(0.01, min(25.0, packet_loss_pct)), 3),
            )
        )

    effective_thresholds = dict(DEFAULT_SLA_THRESHOLDS)
    if sla_thresholds is not None:
        for slice_name in SLICES:
            if slice_name in sla_thresholds:
                effective_thresholds[slice_name] = sla_thresholds[slice_name]

    summary, overall_violation_count, overall_violation_rate = _build_slice_summary(
        metrics=metrics,
        load=load,
        sla_thresholds=effective_thresholds,
    )

    return SimulationResult(
        mode=mode,
        device_metrics=metrics,
        slice_summary=summary,
        overall_sla_violation_count=overall_violation_count,
        overall_sla_violation_rate_pct=overall_violation_rate,
        fairness_index=_calculate_fairness_index(metrics=metrics),
        utility_score=_calculate_utility_score(metrics=metrics),
    )


def _build_slice_summary(
    metrics: list[DeviceMetrics],
    load: Mapping[str, float],
    sla_thresholds: Mapping[str, SliceSlaThreshold],
) -> tuple[dict[str, SliceSummary], int, float]:
    """Aggregates per-device metrics into per-slice KPI summaries."""
    grouped: dict[str, list[DeviceMetrics]] = {slice_name: [] for slice_name in SLICES}

    for record in metrics:
        grouped[record.slice_name].append(record)

    summary: dict[str, SliceSummary] = {}
    overall_violation_count = 0
    total_devices = len(metrics)

    for slice_name in SLICES:
        records = grouped[slice_name]
        threshold = sla_thresholds[slice_name]

        if not records:
            summary[slice_name] = SliceSummary(
                device_count=0,
                avg_latency_ms=0.0,
                p95_latency_ms=0.0,
                p99_latency_ms=0.0,
                avg_throughput_mbps=0.0,
                avg_packet_loss_pct=0.0,
                sla_violation_count=0,
                sla_violation_rate_pct=0.0,
                load_ratio=round(load[slice_name], 3),
            )
            continue

        latencies = [item.latency_ms for item in records]
        violations = _count_sla_violations(records=records, threshold=threshold)
        violation_rate = (violations / len(records)) * 100.0
        overall_violation_count += violations

        summary[slice_name] = SliceSummary(
            device_count=len(records),
            avg_latency_ms=round(mean(item.latency_ms for item in records), 3),
            p95_latency_ms=round(_percentile(latencies, 95.0), 3),
            p99_latency_ms=round(_percentile(latencies, 99.0), 3),
            avg_throughput_mbps=round(mean(item.throughput_mbps for item in records), 3),
            avg_packet_loss_pct=round(mean(item.packet_loss_pct for item in records), 3),
            sla_violation_count=violations,
            sla_violation_rate_pct=round(violation_rate, 3),
            load_ratio=round(load[slice_name], 3),
        )

    overall_rate = 0.0 if total_devices == 0 else (overall_violation_count / total_devices) * 100.0
    return summary, overall_violation_count, round(overall_rate, 3)


def _count_sla_violations(
    records: list[DeviceMetrics],
    threshold: SliceSlaThreshold,
) -> int:
    """Counts devices violating at least one SLA threshold in a slice."""
    violations = 0

    for record in records:
        latency_violation = (
            threshold.max_latency_ms is not None and record.latency_ms > threshold.max_latency_ms
        )
        throughput_violation = (
            threshold.min_throughput_mbps is not None
            and record.throughput_mbps < threshold.min_throughput_mbps
        )
        loss_violation = (
            threshold.max_packet_loss_pct is not None
            and record.packet_loss_pct > threshold.max_packet_loss_pct
        )

        if latency_violation or throughput_violation or loss_violation:
            violations += 1

    return violations


def _percentile(values: list[float], percentile: float) -> float:
    """Computes percentile using linear interpolation between nearest ranks."""
    if not values:
        return 0.0

    sorted_values = sorted(values)
    if len(sorted_values) == 1:
        return sorted_values[0]

    rank = (percentile / 100.0) * (len(sorted_values) - 1)
    lower = int(rank)
    upper = min(lower + 1, len(sorted_values) - 1)
    weight = rank - lower

    return sorted_values[lower] * (1.0 - weight) + sorted_values[upper] * weight


def _calculate_fairness_index(metrics: list[DeviceMetrics]) -> float:
    """Computes Jain fairness index from total per-slice throughput."""
    throughputs = {slice_name: 0.0 for slice_name in SLICES}
    for record in metrics:
        throughputs[record.slice_name] += record.throughput_mbps

    values = list(throughputs.values())
    numerator = sum(values) ** 2
    denominator = len(values) * sum(value * value for value in values)

    if denominator == 0:
        return 0.0

    return round(numerator / denominator, 4)


def _calculate_utility_score(metrics: list[DeviceMetrics]) -> float:
    """Computes a bounded utility score from throughput, latency, and loss."""
    if not metrics:
        return 0.0

    avg_latency = mean(item.latency_ms for item in metrics)
    avg_throughput = mean(item.throughput_mbps for item in metrics)
    avg_packet_loss = mean(item.packet_loss_pct for item in metrics)

    throughput_component = min(1.0, avg_throughput / 25.0)
    latency_component = 1.0 / (1.0 + (avg_latency / 25.0))
    loss_component = 1.0 / (1.0 + (avg_packet_loss / 2.0))

    score = (0.40 * throughput_component) + (0.35 * latency_component) + (0.25 * loss_component)
    return round(score, 4)


def _is_dynamic_mode(mode: str) -> bool:
    """Returns true for dynamic-style policies including PSDAS variants."""
    normalized = mode.strip().lower()
    return normalized == "dynamic" or normalized.startswith("psdas")
